name: llama
model:
  pretrained_model_name_or_path: "meta-llama/Meta-Llama-3.1-70B"
  cache_dir: "/home/mzhang/models/llama-3_1-70b" # Set this to where you want to save checkpoint weights
  return_dict: true
  load_in_8bit: false
  load_in_4bit: false
  device_map: auto
  low_cpu_mem_usage: true
  torch_dtype: bfloat16
  attn_implementation: sdpa
  rope_theta: 500000.0
  rope_scaling:
    factor: 8.0
    low_freq_factor: 1.0
    high_freq_factor: 4.0
    original_max_position_embeddings: 8192
    # rope_type: llama3
    type: llama3

attention:
  attention_type: softmax
